# Autogenerated wrapper script for yaxt_jll for aarch64-apple-darwin-mpi+openmpi
export libyaxt_c

using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("yaxt")
JLLWrappers.@declare_library_product(libyaxt_c, "@rpath/libyaxt_c.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libyaxt_c,
        "lib/libyaxt_c.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
