# Autogenerated wrapper script for yaxt_jll for armv7l-linux-musleabihf-mpi+mpich
export libyaxt_c

using MPICH_jll
JLLWrappers.@generate_wrapper_header("yaxt")
JLLWrappers.@declare_library_product(libyaxt_c, "libyaxt_c.so.1")
function __init__()
    JLLWrappers.@generate_init_header(MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libyaxt_c,
        "lib/libyaxt_c.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
