# Autogenerated wrapper script for yaxt_jll for i686-linux-musl-mpi+mpiabi
export libyaxt_c

using MPIABI_jll
JLLWrappers.@generate_wrapper_header("yaxt")
JLLWrappers.@declare_library_product(libyaxt_c, "libyaxt_c.so.1")
function __init__()
    JLLWrappers.@generate_init_header(MPIABI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libyaxt_c,
        "lib/libyaxt_c.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
